package:
  name: amplify
  version: 0.0.1

source:
  git_url: https://github.com/rchapman2000/AmpLify.git


requirements:
  build:
 
  run:
    - python
    - fastqc
    - bowtie2
    - bedtools
    - bzip2
    - trimmomatic
    - samtools
    - bcftools
    - pyVCF
    - tqdm
    - biopython
    - primerclip

about:
  home: https://github.com/rchapman2000/AmpLify
  license: MIT License
  license_file: LICENSE
